### ISSUE TITLE
NullPointerException when numbers separated by "-" 

### ISSUE THREAD

**Issue by mghalwash** [jianlins/FastContext#4]
When there are two numbers separated by "-" the code gives null pointer exception 
Exception in thread "main" java.lang.NullPointerException
        at edu.utah.bmi.nlp.fastcontext.ContextRuleProcessor.processDigits(ContextRuleProcessor.java:290)
        at edu.utah.bmi.nlp.fastcontext.ContextRuleProcessor.processRules(ContextRuleProcessor.java:237)
        at edu.utah.bmi.nlp.fastcontext.ContextRuleProcessor.processRules(ContextRuleProcessor.java:202)
        at edu.utah.bmi.nlp.fastcontext.FastContext.processContextWEvidence(FastContext.java:147)
        at edu.utah.bmi.nlp.fastcontext.FastContext.processContextWEvidence(FastContext.java:138)
        at edu.utah.bmi.nlp.fastcontext.TestFastContextAPIs.test6(TestFastContextAPIs.java:119)
        at edu.utah.bmi.nlp.fastcontext.TestFastContextAPIs.main(TestFastContextAPIs.java:147)

I did debug the code and found that line 290 in  ContextRuleProcessor has the problem 

You might need to change 
"HashMap ruletmp = (HashMap) rule.get(ruleDigit + "");"
to 
"HashMap ruletmp = (HashMap) rule.get(num);" 

That solves the problem. 

Here is MWE: 

FastContext fc = new FastContext("./conf/context.txt");
String inputString = "Vitals - Tm=Tc:98.2 (range 97.0-98.2 o/n) HR:64-86 myocardial infarction";
String concept = "myocardial infarction";
int conceptBeginOffset = inputString.indexOf(concept);
int conceptEndOffset = conceptBeginOffset + concept.length();
LinkedHashMap<String, ConTextSpan> matches = fc.processContextWEvidence(inputString, conceptBeginOffset, conceptEndOffset, 30);

**Comment by jianlins** [comment]
Thank you! Updated. In fact, how the tokenizer works matters. In general, it is more common to tokenize the number-number into three tokens rather than one token. The method "processContextWEvidence" uses a simple way to tokenize the input string, which is just for demonstration only, not recommended.  
I would recommend to use the following tokenizer: 
https://github.com/jianlins/rush
